### ISSUE TITLE
Error 'xml.etree.ElementTree.Element' object has no attribute 'getchildren' when listing log in Python 3.9.x

### ISSUE THREAD

**Issue by mellotanica** [dsoprea/PySvn#175]
when accessing a repository log with `default_log()` function using Python 3.9 an exception is risen, the used function seems to have been removed from xml library:

https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren

**Comment by mellotanica** [comment]
looking at the master branch code, the issue has already been solved.
yet the latest release package does not work with python 3.9

**Comment by Grandement** [comment]
I have noticed that the fix is not included in the zip or tar.gz file. It is mentioned in the change notes but unfortunately not in the final archive. Can you create a new release which includes the fix? In other words the common.py file in the archives still contains the getchild stuff.

**Comment by jimmydevine** [comment]
no longer maintained?

**Comment by mj-fox** [comment]
Sadly still an issue in python 3.11, package installed via PIP

**Comment by JavaScriptDude** [comment]
Confirmed issue in 3.11. Confirmed its working fine in 3.7.9.
